apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-pub-gke-delhi
  labels:
    client: internal
    version: 1.0.0
    environtment: dev
  annotations:
      description: Practice Kubernetes Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-pub
  template:
    metadata:
      name: poc-pub-pod
      labels:
        app: poc-pub
    spec:
      containers:
        - name: poc-pub
          image: asia-south2-docker.pkg.dev/hbl-poc-digfac-anthos-prj/poc-pub-repo-delhi/poc-pub-image-delhi:v1
          ports:
            - containerPort: 7000
          env:
            - name: DB_HOST
              value: "34.131.143.71"
            - name: PORT
              value: "7000"
            - name: DB_SET
              value: "hdfcset3"
            - name: DB_NAME_SPACE
              value: "hdfc-poc"