version: "3.9"  # optional since v1.27.0
services:
  # db:
  #   image: aerospike/aerospike-server-enterprise:latest
  #   container_name: aerospike_db
  #   environment:
  #     - FEATURE_KEY_FILE=/aerospike/etc/evaluation-features.conf
  #     - NAMESPACE=test
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - /home/cbarik/aerospike:/aerospike/etc
  poc-pub:
    build: .
    ports:
      - 7000:7000
    expose:
      - 7000
    # depends_on:
    #   - db
    environment:
      - DB_HOST=34.131.143.71
      - DB_SET=hdfcset3
      - DB_NAME_SPACE=hdfc-poc

    # volumes:
    #   - .:/code
    #   - logvolume01:/var/log
    # links:
    #   - redis
# volumes:
#   logvolume01: {}