# syntax=docker/dockerfile:1

FROM golang:1.16-alpine as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o main ./cmd/server/

FROM golang:1.16-alpine

WORKDIR /out
COPY --from=builder /app/main .
CMD ["/out/main"]