// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AeroDBService is an autogenerated mock type for the AeroDBService type
type AeroDBService struct {
	mock.Mock
}

// GetRecord provides a mock function with given fields: ctx, keyString
func (_m *AeroDBService) GetRecord(ctx context.Context, keyString string) error {
	ret := _m.Called(ctx, keyString)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, keyString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRecord provides a mock function with given fields: ctx, keyString
func (_m *AeroDBService) InsertRecord(ctx context.Context, keyString string) error {
	ret := _m.Called(ctx, keyString)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, keyString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
