// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PubSubClient is an autogenerated mock type for the PubSubClient type
type PubSubClient struct {
	mock.Mock
}

// CloseClient provides a mock function with given fields:
func (_m *PubSubClient) CloseClient() {
	_m.Called()
}

// PublishMessage provides a mock function with given fields: ctx, msg
func (_m *PubSubClient) PublishMessage(ctx context.Context, msg string) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
